swagger:
    enable: true
spring:
    datasource:
        url: jdbc:h2:mem:RealH2InUserd;DB_CLOSE_DELAY=-1;MODE=MYSQL
    h2:
        console:
            enabled: true
            path: /h2
security:
    oauth2:
        client:
            client-id: client
            client-secret: 123456
    user:
        name: admin
        password: admin
mybatis:
    configuration:
        mapUnderscoreToCamelCase: true